name: Deploy to GitHub Pages
on:
  push:
    branches: [ develop/ramdev ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: cd scope && npm ci
      - run: cd scope && npm run build
      - run: cp scope/dist/index.html scope/dist/404.html  # for SPA routing
      - uses: actions/upload-pages-artifact@v3
        with:
          path: 'scope/dist'

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
